### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Paul-Gallagher**

### CODE REVIEW

**Comment by Paul-Gallagher** [comment]
So, I imagine this is how things would go

- someone makes a change to one of your files
- they create a 'pull request'   (asking you to pull their changes into your code)
- you review the changes and approve or deny or ask for alterations
- finally, you merge the changes in (and the task is automatically moved to done in your kanban)

**Comment by Paul-Gallagher** [comment]
hint: _(if you haven't already seen this)_

- open the pull request
- review any notes
- click on the files-changed button (top of screen)
- review / comment on / ask for changes   (there's a green `review changes` button)

**Review by Jeremy-James-UK — COMMENTED** [review]
Superb! Will approve now.

**Review by Jeremy-James-UK — APPROVED** [review]

**Comment by Paul-Gallagher** [comment]
Now you gotta press the `merge pull request` button

**Comment by Jeremy-James-UK** [comment]
Now I've approved it can't you do the merge, or does it have to be me?

**Pull request merged**
